name: Android CI

on:
  pull_request :
    branches : [ main ]
  push :
    branches : [ main ]

jobs:
  test-feature:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
      - name: Lint
        run: ./gradlew lintDebug